import { APP_CONFIG } from "./config.js";

const keys={records:"stph-records",questions:"stph-questions",timer:"stph-timer"};
const $=id=>document.getElementById(id); const state={records:load(keys.records,[]),questions:load(keys.questions,[]),timer:load(keys.timer,{remaining:1500,running:false,startedAt:null}),interval:null,current:null};
function load(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}} function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
function today(){return new Date().toISOString().slice(0,10)} function fmt(s){s=Math.max(0,Math.round(s));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`} function minutes(){return state.records.filter(r=>r.date===today()).reduce((a,r)=>a+r.minutes,0)}
function show(screen){document.querySelectorAll("[data-screen]").forEach(x=>x.classList.toggle("hidden",x.dataset.screen!==screen));document.querySelectorAll("[data-screen-link]").forEach(x=>x.classList.toggle("active",x.dataset.screenLink===screen));if(screen==="review")renderReviews();if(screen==="records")renderRecords()}
function renderTimer(){let remain=state.timer.remaining;if(state.timer.running&&state.timer.startedAt)remain=Math.max(0,state.timer.remaining-Math.floor((Date.now()-state.timer.startedAt)/1000));$("timerDisplay").textContent=fmt(remain);$("startButton").textContent=state.timer.running?"実行中":"開始";$("startButton").disabled=state.timer.running;$("pauseButton").disabled=!state.timer.running;$("todayMinutes").textContent=`${minutes()}分`;$("questionCount").textContent=state.questions.filter(q=>q.savedAt?.slice(0,10)===today()).length;$("reviewCount").textContent=state.questions.filter(q=>!q.reviewed).length}
function tick(){renderTimer();if(state.timer.running&&state.timer.startedAt&&Date.now()-new Date(state.timer.startedAt).getTime()>=state.timer.remaining*1000){recordSession(state.timer.remaining);state.timer={remaining:Number($("focusMinutes").value)*60,running:false,startedAt:null};save(keys.timer,state.timer);alert("集中時間が終了しました。学習時間を記録しました。");renderTimer()}}
function recordSession(sec){if(sec<1)return;const subject=$("subjectInput").value||"その他";state.records.push({schemaVersion:APP_CONFIG.schemaVersion,sourceApp:APP_CONFIG.sourceApp,id:crypto.randomUUID(),date:today(),subject,minutes:Math.max(1,Math.round(sec/60)),createdAt:new Date().toISOString(),sessionCount:1});save(keys.records,state.records)}
$("startButton").onclick=()=>{state.timer.running=true;state.timer.startedAt=new Date().toISOString();save(keys.timer,state.timer);renderTimer()};$("pauseButton").onclick=()=>{const remain=Math.max(0,state.timer.remaining-Math.floor((Date.now()-new Date(state.timer.startedAt).getTime())/1000));state.timer={remaining:remain,running:false,startedAt:null};save(keys.timer,state.timer);renderTimer()};$("resetButton").onclick=()=>{state.timer={remaining:Number($("focusMinutes").value)*60,running:false,startedAt:null};save(keys.timer,state.timer);renderTimer()};$("focusMinutes").onchange=()=>{if(!state.timer.running){state.timer.remaining=Number($("focusMinutes").value)*60;save(keys.timer,state.timer);renderTimer()}};$("subjectInput").onchange=()=>$("timerSubjectLabel").textContent=$("subjectInput").value||"科目未選択";
document.querySelectorAll("[data-screen-link]").forEach(b=>b.onclick=()=>show(b.dataset.screenLink));
function resize(file){return new Promise((resolve,reject)=>{if(!file||!file.type.startsWith("image/")){reject(new Error("画像ファイルを選択してください"));return}const img=new Image;img.onload=()=>{const scale=Math.min(1,APP_CONFIG.imageMaxWidth/img.width,APP_CONFIG.imageMaxHeight/img.height),c=document.createElement("canvas");c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL("image/jpeg",APP_CONFIG.jpegQuality))};img.onerror=()=>reject(new Error("画像を読み込めませんでした"));img.src=URL.createObjectURL(file)})}
async function handleImage(e){try{$("imagePreview").src=await resize(e.target.files[0]);$("imagePreview").classList.remove("hidden");$("solveButton").disabled=false;$("questionStatus").textContent="画像を確認して解析できます"}catch(err){$("questionStatus").textContent=err.message}}
$("cameraButton").onclick=()=>$ ("cameraInput").click();$("libraryButton").onclick=()=>$ ("libraryInput").click();$("cameraInput").onchange=handleImage;$("libraryInput").onchange=handleImage;
$("solveButton").onclick=async()=>{if(state.questions.filter(q=>q.savedAt?.slice(0,10)===today()).length>=APP_CONFIG.dailyQuestionLimit){$("questionStatus").textContent=`本日の利用上限（${APP_CONFIG.dailyQuestionLimit}問）に達しました`;return}$("solveButton").disabled=true;$("questionStatus").textContent="解析中です。しばらくお待ちください。";try{const res=await fetch("/api/solve-problem",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image:$ ("imagePreview").src,subject:$("questionSubject").value,model:$("analysisModel").value})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"解析に失敗しました");state.current=data;renderSolution();$("questionStatus").textContent="解析が完了しました"}catch(err){$("questionStatus").textContent=err.message||"解析できませんでした。画像や通信状態を確認してください"}finally{$("solveButton").disabled=false}};
function renderSolution(){const q=state.current;$("solution").classList.remove("hidden");$("problemText").textContent=q.problemText||"問題文を読み取れませんでした";$("hint").textContent=q.hint||"ありません";$("steps").innerHTML=(q.steps||[]).map((s,i)=>`<p>${i+1}. ${escapeHtml(s)}</p>`).join("");$("finalAnswer").textContent=q.finalAnswer||"解答できません";$("explanation").textContent=q.explanation||"";$("followUpArea").classList.remove("hidden");$("followUpList").innerHTML="";$("saveQuestionButton").disabled=false}function escapeHtml(s){return String(s).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
$("saveQuestionButton").onclick=()=>{if(!state.current)return;const q={schemaVersion:APP_CONFIG.schemaVersion,sourceApp:APP_CONFIG.sourceApp,id:crypto.randomUUID(),savedAt:new Date().toISOString(),subject:state.current.subject||$("questionSubject").value||"その他",reviewed:false,image:$("imagePreview").src,...state.current};state.questions=[q,...state.questions].slice(0,APP_CONFIG.storageQuestionLimit);save(keys.questions,state.questions);$("saveQuestionButton").disabled=true;$("questionStatus").textContent="復習に保存しました";renderTimer()};
$("followUpButton").onclick=async()=>{const followUp=$("followUpInput").value.trim();if(!followUp||!state.current)return;$("followUpButton").disabled=true;$("followUpStatus").textContent="追加回答を作成中です。";try{const res=await fetch("/api/solve-problem",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image:$("imagePreview").src,subject:$("questionSubject").value,model:$("analysisModel").value,answer:state.current,followUp})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"追加質問に回答できませんでした");const item={question:followUp,answer:data};state.current.followUps=[...(state.current.followUps||[]),item];$("followUpList").insertAdjacentHTML("beforeend",`<article class="follow-up-item"><strong>${escapeHtml(followUp)}</strong><p>${escapeHtml(data.explanation||data.finalAnswer||"回答を取得しました")}</p></article>`);$("followUpInput").value="";$("followUpStatus").textContent="追加回答が完了しました"}catch(err){$("followUpStatus").textContent=err.message}finally{$("followUpButton").disabled=false}};
function renderReviews(){const filter=$("reviewFilter").value,old=$("reviewSort").value==="old";let qs=state.questions.filter(q=>!filter||q.subject===filter).sort((a,b)=>old?a.savedAt.localeCompare(b.savedAt):b.savedAt.localeCompare(a.savedAt));$("reviewList").innerHTML=qs.length?qs.map(q=>`<article class="panel"><details><summary>${escapeHtml(q.subject)}・${escapeHtml(q.topic||"単元未設定")}</summary><p>${escapeHtml(q.problemText||"問題文なし")}</p><p>${escapeHtml(q.finalAnswer||"")}</p><p>${escapeHtml(q.explanation||"")}</p>${(q.followUps||[]).map(f=>`<div class="follow-up-item"><strong>${escapeHtml(f.question)}</strong><p>${escapeHtml(f.answer?.explanation||f.answer?.finalAnswer||"")}</p></div>`).join("")}</details><button data-review="${q.id}">${q.reviewed?"未復習に戻す":"復習済みにする"}</button><button class="quiet" data-delete="${q.id}">削除</button></article>`).join(""):"<p class='help'>保存した問題はまだありません。</p>";document.querySelectorAll("[data-review]").forEach(b=>b.onclick=()=>{const q=state.questions.find(x=>x.id===b.dataset.review);q.reviewed=!q.reviewed;save(keys.questions,state.questions);renderReviews();renderTimer()});document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{state.questions=state.questions.filter(x=>x.id!==b.dataset.delete);save(keys.questions,state.questions);renderReviews();renderTimer()})}$("reviewFilter").onchange=renderReviews;$("reviewSort").onchange=renderReviews;
function renderRecords(){const tm=minutes();$("recordToday").textContent=`${tm}分`;$("recordWeek").textContent=`${state.records.reduce((a,r)=>a+r.minutes,0)}分`;$("recordQuestions").textContent=state.questions.length;const by={};state.records.forEach(r=>by[r.subject]=(by[r.subject]||0)+r.minutes);$("subjectRecords").innerHTML=Object.entries(by).map(([s,m])=>`<p>${escapeHtml(s)}：${m}分</p>`).join("")||"<p class='help'>学習記録はまだありません。</p>"}
if(state.timer.running&&!state.timer.startedAt){state.timer.running=false}setInterval(tick,1000);tick();

$("deleteAllQuestionsButton").onclick=()=>{if(!state.questions.length)return;if(confirm("保存した問題をすべて削除しますか？")){state.questions=[];save(keys.questions,state.questions);renderReviews();renderTimer()}};
$("saveDataButton").onclick=()=>{const backup={schemaVersion:APP_CONFIG.schemaVersion,sourceApp:APP_CONFIG.sourceApp,exportedAt:new Date().toISOString(),records:state.records,questions:state.questions,timer:state.timer};const blob=new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="study-support-backup-"+today()+".json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$("saveDataStatus").textContent="データを保存しました";setTimeout(()=>$("saveDataStatus").textContent="",3000)};
